export interface Personal {
    id: number,
    nombre: string,
    apellido: string,
    password: string,
    fecha_inicio: string,
    tipo: string,
    ci: string,
    correo: string,
    telefono: string,
    direccion: string,
    salario: string,
    imagen: string,
    farmacia_id: string,
}
